# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.22.0-rc3-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.22.0-rc3-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /comp_neuro/Software/CARLsim6

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /comp_neuro/Software/CARLsim6/.build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.22.0-rc3-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.22.0-rc3-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"benchmark\" \"carlsim\" \"carlsim-simple-weight-tuner\" \"carlsim-spike-generators\" \"carlsim-stopwatch\" \"carlsim-visual-stimulus\" \"hello_world\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake-3.22.0-rc3-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake-3.22.0-rc3-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake-3.22.0-rc3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake-3.22.0-rc3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake-3.22.0-rc3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake-3.22.0-rc3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /comp_neuro/Software/CARLsim6/.build && $(CMAKE_COMMAND) -E cmake_progress_start /comp_neuro/Software/CARLsim6/.build/CMakeFiles /comp_neuro/Software/CARLsim6/.build/projects/hello_world//CMakeFiles/progress.marks
	cd /comp_neuro/Software/CARLsim6/.build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projects/hello_world/all
	$(CMAKE_COMMAND) -E cmake_progress_start /comp_neuro/Software/CARLsim6/.build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /comp_neuro/Software/CARLsim6/.build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projects/hello_world/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /comp_neuro/Software/CARLsim6/.build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projects/hello_world/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /comp_neuro/Software/CARLsim6/.build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projects/hello_world/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /comp_neuro/Software/CARLsim6/.build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
projects/hello_world/CMakeFiles/hello_world.dir/rule:
	cd /comp_neuro/Software/CARLsim6/.build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projects/hello_world/CMakeFiles/hello_world.dir/rule
.PHONY : projects/hello_world/CMakeFiles/hello_world.dir/rule

# Convenience name for target.
hello_world: projects/hello_world/CMakeFiles/hello_world.dir/rule
.PHONY : hello_world

# fast build rule for target.
hello_world/fast:
	cd /comp_neuro/Software/CARLsim6/.build && $(MAKE) $(MAKESILENT) -f projects/hello_world/CMakeFiles/hello_world.dir/build.make projects/hello_world/CMakeFiles/hello_world.dir/build
.PHONY : hello_world/fast

src/main_hello_world.o: src/main_hello_world.cpp.o
.PHONY : src/main_hello_world.o

# target to build an object file
src/main_hello_world.cpp.o:
	cd /comp_neuro/Software/CARLsim6/.build && $(MAKE) $(MAKESILENT) -f projects/hello_world/CMakeFiles/hello_world.dir/build.make projects/hello_world/CMakeFiles/hello_world.dir/src/main_hello_world.cpp.o
.PHONY : src/main_hello_world.cpp.o

src/main_hello_world.i: src/main_hello_world.cpp.i
.PHONY : src/main_hello_world.i

# target to preprocess a source file
src/main_hello_world.cpp.i:
	cd /comp_neuro/Software/CARLsim6/.build && $(MAKE) $(MAKESILENT) -f projects/hello_world/CMakeFiles/hello_world.dir/build.make projects/hello_world/CMakeFiles/hello_world.dir/src/main_hello_world.cpp.i
.PHONY : src/main_hello_world.cpp.i

src/main_hello_world.s: src/main_hello_world.cpp.s
.PHONY : src/main_hello_world.s

# target to generate assembly for a file
src/main_hello_world.cpp.s:
	cd /comp_neuro/Software/CARLsim6/.build && $(MAKE) $(MAKESILENT) -f projects/hello_world/CMakeFiles/hello_world.dir/build.make projects/hello_world/CMakeFiles/hello_world.dir/src/main_hello_world.cpp.s
.PHONY : src/main_hello_world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... hello_world"
	@echo "... src/main_hello_world.o"
	@echo "... src/main_hello_world.i"
	@echo "... src/main_hello_world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /comp_neuro/Software/CARLsim6/.build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

